# Tarefa 02

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [147]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [148]:
# 1) Seu código aqui
df_mat['percentual acerto'] = (df_mat['Qt_acertos']/24) * 100
df_por['percentual acerto'] = (df_por['Qt_acertos']/18) * 100
df_geo['percentual acerto'] = (df_geo['Qt_acertos']/8) * 100
df_ing['percentual acerto'] = (df_ing['Qt_acertos']/8) * 100
df_his['percentual acerto'] = (df_his['Qt_acertos']/8) * 100
df_fis['percentual acerto'] = (df_fis['Qt_acertos']/12) * 100
df_qui['percentual acerto'] = (df_qui['Qt_acertos']/12) * 100

In [149]:
# 2) Seu código aqui
df = pd.DataFrame(data=df_mat['Qt_acertos'] + df_por['Qt_acertos'] + df_geo['Qt_acertos'] + df_ing['Qt_acertos'] + df_his['Qt_acertos'] + df_fis['Qt_acertos'] + df_qui['Qt_acertos'])
df.rename(columns={'Qt_acertos':'Qt_total_acertos'}, inplace = True)
df

    Qt_total_acertos
0                 35
1                 48
2                 50
3                 32
4                 30
5                 50
6                 29
7                 49
8                 58
9                 39
10                31
11                43
12                42
13                21
14                31
15                40
16                30
17                52
18                50
19                37
20                53
21                36
22                26
23                26
24                50
25                27
26                40
27                50
28                39
29                44
..               ...
70                62
71                53
72                50
73                37
74                39
75                42
76                35
77                53
78                66
79                33
80                45
81                55
82                43
83                42
84                26
85                37
86                33
87                36
88                50
89                63
90                31
91                27
92                40
93                56
94                25
95                34
96                27
97                40
98                40
99                42

[100 rows x 1 columns]

In [150]:
# 3) Seu código aqui
df['percentual_geral'] = (df['Qt_total_acertos']/90) * 100
df

    Qt_total_acertos  percentual_geral
0                 35         38.888889
1                 48         53.333333
2                 50         55.555556
3                 32         35.555556
4                 30         33.333333
5                 50         55.555556
6                 29         32.222222
7                 49         54.444444
8                 58         64.444444
9                 39         43.333333
10                31         34.444444
11                43         47.777778
12                42         46.666667
13                21         23.333333
14                31         34.444444
15                40         44.444444
16                30         33.333333
17                52         57.777778
18                50         55.555556
19                37         41.111111
20                53         58.888889
21                36         40.000000
22                26         28.888889
23                26         28.888889
24                50         55.555556
25                27         30.000000
26                40         44.444444
27                50         55.555556
28                39         43.333333
29                44         48.888889
..               ...               ...
70                62         68.888889
71                53         58.888889
72                50         55.555556
73                37         41.111111
74                39         43.333333
75                42         46.666667
76                35         38.888889
77                53         58.888889
78                66         73.333333
79                33         36.666667
80                45         50.000000
81                55         61.111111
82                43         47.777778
83                42         46.666667
84                26         28.888889
85                37         41.111111
86                33         36.666667
87                36         40.000000
88                50         55.555556
89                63         70.000000
90                31         34.444444
91                27         30.000000
92                40         44.444444
93                56         62.222222
94                25         27.777778
95                34         37.777778
96                27         30.000000
97                40         44.444444
98                40         44.444444
99                42         46.666667

[100 rows x 2 columns]

In [151]:
# 4) Seu código aqui
df['fl_aprovado'] = df['Qt_total_acertos'] >= 45
print(f'foram aprovados {df["fl_aprovado"].sum()} alunos')

foram aprovados 34 alunos

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [152]:
# seu código aqui
df_new = pd.DataFrame(data=df)

df_new['Qt_acertos_mat'] = df_mat['Qt_acertos']
df_new['Qt_acertos_fis'] = df_fis['Qt_acertos']
df_new['Qt_acertos_qui'] = df_qui['Qt_acertos']
df_new['Qt_acertos_geo'] = df_geo['Qt_acertos']
df_new['Qt_acertos_his'] = df_his['Qt_acertos']

In [153]:
def esta_reprovado_por_0(linha):
    
    mat_fis_qui_0 = any([nota == 0 for nota in linha[['Qt_acertos_mat','Qt_acertos_fis','Qt_acertos_qui']].values])
    return mat_fis_qui_0
df_new['fl_reprovado_por_0'] = df_new.apply(esta_reprovado_por_0, axis=1)
df_new

,Qt_total_acertos,percentual_geral,fl_aprovado,Qt_acertos_mat,Qt_acertos_fis,Qt_acertos_qui,Qt_acertos_geo,Qt_acertos_his,fl_reprovado_por_0
0,35,38.888889,False,6,8,3,7,1,False
1,48,53.333333,True,19,11,8,0,0,False
2,50,55.555556,True,14,4,4,0,7,False
3,32,35.555556,False,10,0,8,3,0,True
4,30,33.333333,False,7,9,3,2,0,False
5,50,55.555556,True,20,9,9,5,2,False
6,29,32.222222,False,6,0,4,7,5,True
7,49,54.444444,True,18,1,8,4,7,False
8,58,64.444444,True,22,5,7,2,6,False
9,39,43.333333,False,10,8,2,3,4,False
10,31,34.444444,False,10,7,0,3,1,True
11,43,47.777778,False,23,4,2,2,6,False
12,42,46.666667,False,20,0,3,3,1,True
13,21,23.333333,False,3,6,1,2,2,False
14,31,34.444444,False,7,4,0,1,1,True
15,40,44.444444,False,23,5,6,2,0,False
16,30,33.333333,False,2,6,7,6,7,False
17,52,57.777778,True,21,2,6,2,4,False
18,50,55.555556,True,20,11,4,3,3,False
19,37,41.111111,False,1,9,11,7,1,False
20,53,58.888889,True,23,2,0,6,6,True
21,36,40.000000,False,11,4,6,3,0,False
22,26,28.888889,False,5,5,6,0,3,False
23,26,28.888889,False,1,8,8,0,4,False
24,50,55.555556,True,20,11,2,7,3,False
25,27,30.000000,False,0,4,8,7,0,True
26,40,44.444444,False,11,0,0,6,7,True
27,50,55.555556,True,21,3,0,1,7,True
28,39,43.333333,False,11,4,3,7,5,False
29,44,48.888889,False,16,11,8,0,7,False
...,...,...,...,...,...,...,...,...,...
70,62,68.888889,True,21,11,8,0,5,False
71,53,58.888889,True,17,2,9,7,4,False
72,50,55.555556,True,11,0,9,3,7,True
73,37,41.111111,False,1,0,11,2,3,True
74,39,43.333333,False,9,7,0,0,5,True
75,42,46.666667,False,3,9,5,7,6,False
76,35,38.888889,False,13,10,6,3,2,False
77,53,58.888889,True,15,11,7,5,6,False
78,66,73.333333,True,14,11,9,7,7,False
79,33,36.666667,False,7,1,8,3,3,False
80,45,50.000000,True,13,2,1,5,7,False
81,55,61.111111,True,22,1,10,2,4,False
82,43,47.777778,False,7,2,9,7,1,False
83,42,46.666667,False,20,6,1,5,3,False
84,26,28.888889,False,15,0,4,0,1,True
85,37,41.111111,False,12,9,4,2,5,False
86,33,36.666667,False,17,7,5,0,2,False
87,36,40.000000,False,14,9,2,4,0,False
88,50,55.555556,True,20,9,7,1,7,False
89,63,70.000000,True,23,9,0,7,6,True
90,31,34.444444,False,12,1,5,5,2,False
91,27,30.000000,False,8,2,3,1,3,False
92,40,44.444444,False,14,8,0,1,1,True
93,56,62.222222,True,12,6,6,5,6,False
94,25,27.777778,False,0,3,8,2,1,True
95,34,37.777778,False,6,9,3,7,4,False
96,27,30.000000,False,8,4,3,4,1,False
97,40,44.444444,False,23,1,5,0,4,False
98,40,44.444444,False,0,10,11,3,5,True
99,42,46.666667,False,11,7,2,0,6,False

In [154]:
print(df_new.loc[df_new['fl_reprovado_por_0']]['Qt_acertos_his'].mean())
print(df_new.loc[df_new['fl_reprovado_por_0']]['Qt_acertos_geo'].mean())

3.4347826086956523
3.217391304347826

In [155]:
df_aprovados = df_new.loc[(df_new['fl_aprovado']) & (df_new['fl_reprovado_por_0'] == False)]

In [156]:
df_aprovados

,Qt_total_acertos,percentual_geral,fl_aprovado,Qt_acertos_mat,Qt_acertos_fis,Qt_acertos_qui,Qt_acertos_geo,Qt_acertos_his,fl_reprovado_por_0
1,48,53.333333,True,19,11,8,0,0,False
2,50,55.555556,True,14,4,4,0,7,False
5,50,55.555556,True,20,9,9,5,2,False
7,49,54.444444,True,18,1,8,4,7,False
8,58,64.444444,True,22,5,7,2,6,False
17,52,57.777778,True,21,2,6,2,4,False
18,50,55.555556,True,20,11,4,3,3,False
24,50,55.555556,True,20,11,2,7,3,False
31,54,60.000000,True,15,9,10,3,3,False
34,45,50.000000,True,18,3,3,1,6,False
36,56,62.222222,True,22,4,8,6,1,False
37,52,57.777778,True,19,6,2,5,1,False
39,49,54.444444,True,4,9,8,2,6,False
40,47,52.222222,True,18,5,6,6,6,False
42,48,53.333333,True,20,3,3,7,2,False
45,48,53.333333,True,17,9,4,0,6,False
48,55,61.111111,True,17,9,11,0,5,False
53,45,50.000000,True,14,7,3,3,3,False
60,48,53.333333,True,16,7,9,0,4,False
62,46,51.111111,True,17,1,9,2,7,False
67,46,51.111111,True,21,2,10,7,4,False
70,62,68.888889,True,21,11,8,0,5,False
71,53,58.888889,True,17,2,9,7,4,False
77,53,58.888889,True,15,11,7,5,6,False
78,66,73.333333,True,14,11,9,7,7,False
80,45,50.000000,True,13,2,1,5,7,False
81,55,61.111111,True,22,1,10,2,4,False
88,50,55.555556,True,20,9,7,1,7,False
93,56,62.222222,True,12,6,6,5,6,False

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?

In [169]:
arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'
df = pd.read_csv(arquivo)
df
#Não consigo acessar a base de dados por problemas da base de dados do ministério da saúde.

HTTPError: HTTP Error 403: Forbidden

In [158]:
# 1) Sua solução aqui

In [159]:
# 2)

In [160]:
# 3)

In [ ]:
# 3) solução alternativa

In [ ]:
# 4)

In [ ]:
# 5)

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [ ]:
# 1)

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 4)

In [ ]:
# 5)